# -*- coding: utf-8 -*-
"""ARMA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z4ST5wOT_ti8rQaWROvDcW5B4whRVmbr
"""

import pandas as pd
df=pd.read_csv('')

df

df['index'] = df.index

df

import matplotlib.pyplot as plt

plt.plot(df['index'],df['Open'])

import statsmodels.api as sm

from statsmodels.tsa.arima.model import ARIMA

arma_mod20 = ARIMA(df['Open'], order=(1, 1, 10)).fit()

y=arma_mod20.predict(start=0,end=len(df)-1)

plt.plot(df['index'],y,color='r')
plt.plot(df['index'],df['Open'])

arma_mod20 = ARIMA(df['Open'], order=(1, 1, 10)).fit()

y=arma_mod20.predict(start=0,end=2*len(df)-1)
x=[i for i in range(0,2*len(df))]

plt.plot(x,y,color='r')
#plt.plot(df['index'],df['Open'])

import statsmodels.graphics as grph

grph.tsaplots.plot_acf(df['Open'])

grph.tsaplots.plot_pacf(df['Open'])

arma_mod20.summary()

import sklearn.linear_model as lm

model=lm.LinearRegression().fit(np.array(df['index']).reshape(-1,1),df['Open'])

plt.plot(df['index'],model.predict(np.array(df['index']).reshape(-1,1)))
plt.plot(df['index'],df['Open'],color='r')

model

from scipy import interpolate

f=interpolate.interp1d(df['index'],df['Open'])

f(50)

