# -*- coding: utf-8 -*-
"""inventory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16svMxyJ9uLkLAyihNE1iBeu1B-4WYvZJ
"""

period=[1,2,3]
Demand=[3,2,4]
Setup=[3,7,6]
Holding=[1,3,2]

periods=3

i=0
print(sum(Demand[i+1:]))

def cost(z):
    if z>=0 and z<=3:
        return 10*z
    else:
        return 30+20*(z-3)



def period1(i):
  di=Demand[i]
  ub_range_xiplus1=sum(Demand[i+1:])
  lb_range_xiplus1=0
  range_xiplus1=[lb_range_xiplus1,ub_range_xiplus1]
  print(range_xiplus1)
  zi=[k+Demand[i]-1 for k in range(range_xiplus1[0],range_xiplus1[1]+1)]
  print(zi)
  Ci=[Setup[i]+cost(Zi) for Zi in zi]
  print(Ci)
  h1x2=[Holding[i]*xi_m for xi_m in range(range_xiplus1[0],range_xiplus1[1]+1)]
  print(h1x2)
  cand=[]
  for it in range(len(Ci)):
    cand.append(Ci[it]+h1x2[it])
  print(cand)
  return cand

period1(0)

def periods(i):
  if i==1:
    di=Demand[i]
    lb_range_xiplus1=0
    ub_range_xiplus1=sum(Demand[i+1:])
    range_xiplus1=[lb_range_xiplus1,ub_range_xiplus1]
    print("range_xiplus1=",range_xiplus1)
    xiplus1_arr=[]
    for k in range(range_xiplus1[0],range_xiplus1[1]+1):
      xiplus1_arr.append(k)
    print("xiplus1_arr",xiplus1_arr)
    zi=[]
    for k in range(0,di+ub_range_xiplus1+1):
      zi.append(k)
    print("zi",zi)
    xihiplus1=[]
    for x in range(lb_range_xiplus1,ub_range_xiplus1+1):
      xihiplus1.append(Holding[i]*x)
    print("xihiplus1",xihiplus1)
    costl=[]
    for z in zi:
      if z!=0:
        costl.append(cost(z)+Setup[i])
      else:
        costl.append(cost(z))
    ans=[]
    print("costl",costl)
    for ele in xiplus1_arr:
      tempans=[]
      for f in range(0,Demand[i]+ele+1):
        tempans.append(costl[f]+xihiplus1[ele]+period1(0)[Demand[i]+ele-f])
        print(costl[0]+xihiplus1[1]+period1(0)[3])
      ans.append(tempans)
    finalans=[]
    for row in ans:
      finalans.append(min(row))
    return finalans
  if i==2:
    di=Demand[i]
    lb_range_xiplus1=0
    ub_range_xiplus1=sum(Demand[i+1:])
    range_xiplus1=[lb_range_xiplus1,ub_range_xiplus1]
    print("range_xiplus1=",range_xiplus1)
    xiplus1_arr=[]
    for k in range(range_xiplus1[0],range_xiplus1[1]+1):
      xiplus1_arr.append(k)
    print("xiplus1_arr",xiplus1_arr)
    zi=[]
    for k in range(0,di+ub_range_xiplus1+1):
      zi.append(k)
    print("zi",zi)
    xihiplus1=[]
    for x in range(lb_range_xiplus1,ub_range_xiplus1+1):
      xihiplus1.append(Holding[i]*x)
    print("xihiplus1",xihiplus1)
    costl=[]
    for z in zi:
      if z!=0:
        costl.append(cost(z)+Setup[i])
      else:
        costl.append(cost(z))
    ans=[]
    print("costl",costl)
    for ele in xiplus1_arr:
      tempans=[]
      for f in range(0,Demand[i]+ele+1):
        tempans.append(costl[f]+xihiplus1[ele]+periods(1)[Demand[i]+ele-f])
        #print(costl[0]+xihiplus1[1]+period1(0)[3])
      ans.append(tempans)
    finalans=[]
    for row in ans:
      finalans.append(min(row))
    return finalans

x=periods(1)





print(periods(2))



"""Silver meal"""

